### ISSUE TITLE
Trying to build /packages/transporter

### ISSUE THREAD

**Issue by tur-ing** [Yuyz0112/syncit#10]
When I try to run `npm run build` in `./packages/transporter/` I get the following error:

<img width="1253" alt="Screenshot 2021-01-11 at 18 50 46" src="https://user-images.githubusercontent.com/15199933/104263270-1dd2ec80-543e-11eb-84c2-4295bd73f4d5.png">

**Comment by Yuyz0112** [comment]
Could you try this setup?

```
# in root folder
yarn
yarn lerna run prepublish
cd packages/transporter
yarn build
```

**Comment by tur-ing** [comment]
Worked, thank you!
